module test
stationary test2
manifest mat chemical1
manifest chemical2
manifest x
manifest y

functions

function doThis(mat chem) : mat {
    drain chem3
    drain a
    drain chem
    return chem
}

function doThis2(mat chem, mat chem3, chem4) {
    a = mix chem with chem3
    repeat 4 times {
        drain chem
    }
    b = mix a with chem4
    return b
}

instructions

awesome = mix x with y
a = doThis2(chemical1, chemical2, awesome)
awesome = mix a with b

x = 5 + 5