stationary reagent

module fluorescence

manifest glucose
manifest distilled_water

functions

instructions

result1 = mix 10uL on glucose with 10uL on reagent for 10s
reading1 = detect fluorescence on result1 for 30s
a = mix distilled_water with reagent for 30s
drain a

result2 = mix 10uL on glucose with 20uL on reagent for 10s
reading2 = detect fluorescence on result2 for 30s
a = mix distilled_water with reagent for 30s
drain a

result3 = mix 10uL on glucose with 40uL on reagent for 10s
reading3 = detect fluorescence on result3 for 30s
a = mix distilled_water with reagent for 30s
drain a

result4 = mix 10uL on glucose with 80uL on reagent for 10s
reading4 = detect fluorescence on result4 for 30s
a = mix distilled_water with reagent for 30s
drain a

result5 = mix 10uL on Sample with 10uL on reagent for 10s
reading5 = detect fluorescence on result5 for 30s
a = mix distilled_water with reagent for 30s
drain a