manifest PCRMasterMix

functions

instructions

PCRMix = mix 50 uL of PCRMasterMix with 50 uL of Template for 1s

repeat 50 times {
  heat PCRMix at 95C for 20s
  volumeWeight = Weigh PCRMix

  if (volumeWeight <= 50uL) {
    replacement = mix 25uL of PCRMasterMix with 25uL of Template for 5s
    heat replacement at 95C for 45s
    PCRMix = mix PCRMix with replacement for 5s
  }

  heat PCRMix at 68C for 30s
  heat PCRMix at 95C for 45s
}

heat PCRMix at 68C for 5min