module fluorescence

manifest PCR_Master_Mix
manifest Buffer

functions

instructions

PCRMix = mix 50uL of PCR_Master_Mix with 50uL of Buffer

heat PCRMix at 94c for 2m

repeat 20 times {
  heat PCRMix at 94c for 20s
  heat PCRMix at 50c for 40s
}
DNA_Sensor = detect fluorescence on PCRMix for 30s
if (DNA_Sensor <= 85) {
  drain PCRMix
}

repeat 20 times {
  heat PCRMix at 94c for 20s
  heat PCRMix at 50c for 40s
}
heat PCRMix at 70c for 5m
drain PCRMix