module fluorescence
manifest PCR_Master_Mix
manifest Buffer

functions

instructions

PCR_Master_Mix = mix 50uL of PCRMix with 50uL of Buffer

# Initialization Step
heat PCR_Master_Mix at 94C for 2min

# Denaturation
repeat 20 times {
  heat PCR_Master_Mix at 94C for 20s
  heat PCR_Master_Mix at 50C for 40s
}
DNA_Sensor = detect fluorescence on PCR_Master_Mix for 30s
if (DNA Sensor <= 85) {
  drain PCR_Master_Mix
}

repeat 20 times {
  heat PCR_Master_Mix at 94C for 20s
  heat PCR_Master_Mix at 50C for 40s
}
# Final Elongation
heat PCR_Master_Mix at 70C for 5min

Save PCR_Master_Mix