module fluorescence

stationary Anti_Morphine
stationary Anti_Oxy
stationary Anti_Fentanyl
stationary Anti_Ciprofloxacin
stationary Anti_Heroin

manifest UrineSample

functions

instructions

a = mix 10uL of UrineSample with Anti_Morphine
b = mix 10uL of UrineSample with Anti_Oxy
d = mix 10uL of UrineSample with Anti_Fentanyl
e = mix 10uL of UrineSample with Anti_Ciprofloxacin
g = mix 10uL of UrineSample with Anit_Heroin

MorphineReading = detect fluorescence on a for 5s
OxyReading = detect fluorescence on b for 5s
FentanylReading = detect fluorescence on d for 5s
CiproReading = detect fluorescence on e for 5s
HeroinReading = detect fluorescence on g for 5s

Drain (Anti_Morphine)
Drain (Anti_Oxy)
Drain (Anti_Fentanyl)
Drain (Anti_Ciprofloxcin)
Drain (Anti_Heroin)