module fluorescence

manifest Anti_Morphine
manifest Anti_Oxy
manifest Anti_Fentanyl
manifest Anti_Ciprofloxcin
manifest Anti_Heroin

manifest UrineSample

functions

instructions

a = mix 10uL of UrineSample with Anti_Morphine
b = mix 10uL of UrineSample with Anti_Oxy
cc = mix 10uL of UrineSample with Anti_Fentanyl
d = mix 10uL of UrineSample with Anti_Ciprofloxcin
e = mix 10uL of UrineSample with Anti_Heroin

MorphineReading = detect fluorescence on a for 5s
OxyReading = detect fluorescence on b for 5s
FentanylReading = detect fluorescence on cc for 5s
CiproReading = detect fluorescence on d for 5s
HeroinReading = detect fluorescence on e for 5s

drain Anti_Morphine
drain Anti_Oxy
drain Anti_Fentanyl
drain Anti_Ciprofloxcin
drain Anti_Heroin