stationary ciprofloxacin_enzyme

module fluorescence

manifest distilled_water
manifest ciprofloxacin_conjugate
manifest tmb_substrate
manifest urinesample
manifest stop_reagent

functions

instructions

a = mix 20uL of urinesample to ciprofloxacin_enzyme
b = 100uL of ciprofloxacin_conjugate with a for 60s
heat b at 23 C for 60min
drain b

repeat 5 times {
  temp = mix 250uL of distilled_water to ciprofloxacin_enzyme for 45s
  drain temp
}

d = mix 50uL of tmb_substrate with ciprofloxacin_enzyme
heat d at 25 C for 30m
e = mix ciprofloxacin_enzyme with 100uL of stop_reagent for 60s

urine_reading = detect fluorescence on ciprofloxacin_enzyme for 5m
drain urine_reading