module fluorescence

stationary diazepam_enzyme

manifest urinesample
manifest diazepam_antibody
manifest distilled_water
manifest stop_reagent
manifest hrp_conjugate
manifest tmb_substrate

functions

instructions

a = mix 50uL of urinesample with diazepam_enzyme
b = mix 100uL of diazepam_antibody with a for 60s
heat b at 23c for 30m
drain b

repeat 3 times {
  a = mix 250uL of distilled_water with diazepam_enzyme for 45s
  drain a
}

cc = mix 150uL of hrp_conjugate with diazepam_enzyme
heat cc at 23c for 15m
drain cc

repeat 3 times {
  a = mix 250uL of distilled_water with diazepam_enzyme for 45s
  drain a
}

d = mix 100uL of tmb_substrate with diazepam_enzyme
heat d at 23c for 15m
d = mix diazepam_enzyme with 100uL of stop_reagent for 60s
Negative_Reading = detect fluorescence on d for 30m
drain d