manifest substance_a
manifest dilutant1

First-Dilute = Mix Substance A with Dilutant1
Split First-Dilute into 2 parts:
  1 part to First-Dilute
  1 part to Waste-Droplet
Drain Waste-Droplet

Second-Dilute = Mix First-Dilute with Dilutant2
Split Second-Dilute into 2 parts:
  1 part to Second-Dilute
  1 part to Waste-Droplet
Drain Waste-Droplet

Third Dilute = Mix Second-Dilute with Dilutant3
Split Third-Dilute into 2 parts:
  1 part to Third-Dilute
  1 part to Waste-Droplet
Drain Waste-Droplet

Fourth-Dilute = Mix Substance B with Substance C
Split Fourth-Dilute into 2 parts:
  1 part to Fourth-Dilute
  1 part to Waste-Droplet
Drain Waste-Droplet

Final-Dilute = Mix Third-Dilute with Fourth-Dilute
Split Final-Dilute into 2 parts:
  1 part to Final-Dilute
  1 part to Waste-Droplet
Drain Waste-Droplet

Save Final-Dilute