package phases.inference;

import org.apache.logging.log4j.LogManager;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.Set;

/**
 * @created: 9/7/17
 * @since: 0.1
 * @project: ChemicalCompiler
 */
public enum ChemTypes {
    ACIDS_STRONG_NON_OXIDIZING(1),
    ACIDS_STRONG_OXIDIZING(2),
    ACIDS_CARBOXYLIC(3),
    ALCOHOLS_AND_POLYOLS(4),
    ALDEHYDES(5),
    AMIDES_AND_IMIDES(6),
    AMINES_PHOSPHINES_AND_PYRIDINES(7),
    AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS(8),
    CARBAMATES(9),
    BASES_STRONG(10),
    CYANIDES_INORGANIC(11),
    THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS(12),
    ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS(13),
    ETHERS(14),
    HYDROCARBONS_AROMATIC(16),
    HALOGENATED_ORGANIC_COMPOUNDS(17),
    ISOCYANATES_AND_ISOTHIOCYANATES(18),
    KETONES(19),
    SULFIDES_ORGANIC(20),
    METALS_ALKALI_VERY_ACTIVE(21),
    METALS_ELEMENTAL_AND_POWDER_ACTIVE(22),
    METALS_LESS_REACTIVE(23),
    DIAZONIUM_SALTS(25),
    NITRILES(26),
    NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC(27),
    HYDROCARBONS_ALIPHATIC_UNSATURATED(28),
    HYDROCARBONS_ALIPHATIC_SATURATED(29),
    PEROXIDES_ORGANIC(30),
    PHENOLS_AND_CRESOLS(31),
    SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC(32),
    SULFIDES_INORGANIC(33),
    EPOXIDES(34),
    METAL_HYDRIDES_METAL_ALKYLS_METAL_ARYLS_AND_SILANES(35),
    ANHYDRIDES(37),
    SALTS_ACIDIC(38),
    SALTS_BASIC(39),
    ACYL_HALIDES_SULFONYL_HALIDES_AND_CHLOROFORMATES(40),
    ORGANOMETALLICS(42),
    OXIDIZING_AGENTS_STRONG(44),
    REDUCING_AGENTS_STRONG(45),
    NON_REDOX_ACTIVE_INORGANIC_COMPOUNDS(46),
    FLUORINATED_ORGANIC_COMPOUNDS(47),
    FLUORIDE_SALTS_SOLUBLE(48),
    OXIDIZING_AGENTS_WEAK(49),
    REDUCING_AGENTS_WEAK(50),
    NITRIDES_PHOSPHIDES_CARBIDES_AND_SILICIDES(51),
    CHLOROSILANES(55),
    SILOXANES(58),
    HALOGENATING_AGENTS(59),
    ACIDS_WEAK(60),
    BASES_WEAK(61),
    CARBONATE_SALTS(62),
    ALKYNES_WITH_ACETYLENIC_HYDROGEN(63),
    ALKYNES_WITH_NO_ACETYLENIC_HYDROGEN(64),
    CONJUGATED_DIENES(65),
    ARYL_HALIDES(66),
    AMINES_AROMATIC(68),
    NITRATE_AND_NITRITE_COMPOUNDS_INORGANIC(69),
    ACETALS_KETALS_HEMIACETALS_AND_HEMIKETALS(70),
    ACRYLATES_AND_ACRYLIC_ACIDS(71),
    PHENOLIC_SALTS(72),
    QUATERNARY_AMMONIUM_AND_PHOSPHONIUM_SALTS(73),
    SULFITE_AND_THIOSULFATE_SALTS(74),
    OXIMES(75),
    POLYMERIZABLE_COMPOUNDS(76),
    NOT_CHEMICALLY_REACTIVE(98),
    INSUFFICIENT_INFORMATION_FOR_CLASSIFICATION(99),
    WATER_AND_AQUEOUS_SOLUTIONS(100),
    MAT(128),
    REAL(129),
    NAT(130),
    CONST(131);

    private static Map<Integer, ChemTypes> integerChemTypesMap = new HashMap<Integer, ChemTypes>() {{
        put(1, ACIDS_STRONG_NON_OXIDIZING);
        put(2, ACIDS_STRONG_OXIDIZING);
        put(3, ACIDS_CARBOXYLIC);
        put(4, ALCOHOLS_AND_POLYOLS);
        put(5, ALDEHYDES);
        put(6, AMIDES_AND_IMIDES);
        put(7, AMINES_PHOSPHINES_AND_PYRIDINES);
        put(8, AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS);
        put(9, CARBAMATES);
        put(10, BASES_STRONG);
        put(11, CYANIDES_INORGANIC);
        put(12, THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS);
        put(13, ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS);
        put(14, ETHERS);
        put(16, HYDROCARBONS_AROMATIC);
        put(17, HALOGENATED_ORGANIC_COMPOUNDS);
        put(18, ISOCYANATES_AND_ISOTHIOCYANATES);
        put(19, KETONES);
        put(20, SULFIDES_ORGANIC);
        put(21, METALS_ALKALI_VERY_ACTIVE);
        put(22, METALS_ELEMENTAL_AND_POWDER_ACTIVE);
        put(23, METALS_LESS_REACTIVE);
        put(25, DIAZONIUM_SALTS);
        put(26, NITRILES);
        put(27, NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC);
        put(28, HYDROCARBONS_ALIPHATIC_UNSATURATED);
        put(29, HYDROCARBONS_ALIPHATIC_SATURATED);
        put(30, PEROXIDES_ORGANIC);
        put(31, PHENOLS_AND_CRESOLS);
        put(32, SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC);
        put(33, SULFIDES_INORGANIC);
        put(34, EPOXIDES);
        put(35, METAL_HYDRIDES_METAL_ALKYLS_METAL_ARYLS_AND_SILANES);
        put(37, ANHYDRIDES);
        put(38, SALTS_ACIDIC);
        put(39, SALTS_BASIC);
        put(40, ACYL_HALIDES_SULFONYL_HALIDES_AND_CHLOROFORMATES);
        put(42, ORGANOMETALLICS);
        put(44, OXIDIZING_AGENTS_STRONG);
        put(45, REDUCING_AGENTS_STRONG);
        put(46, NON_REDOX_ACTIVE_INORGANIC_COMPOUNDS);
        put(47, FLUORINATED_ORGANIC_COMPOUNDS);
        put(48, FLUORIDE_SALTS_SOLUBLE);
        put(49, OXIDIZING_AGENTS_WEAK);
        put(50, REDUCING_AGENTS_WEAK);
        put(51, NITRIDES_PHOSPHIDES_CARBIDES_AND_SILICIDES);
        put(55, CHLOROSILANES);
        put(58, SILOXANES);
        put(59, HALOGENATING_AGENTS);
        put(60, ACIDS_WEAK);
        put(61, BASES_WEAK);
        put(62, CARBONATE_SALTS);
        put(63, ALKYNES_WITH_ACETYLENIC_HYDROGEN);
        put(64, ALKYNES_WITH_NO_ACETYLENIC_HYDROGEN);
        put(65, CONJUGATED_DIENES);
        put(66, ARYL_HALIDES);
        put(68, AMINES_AROMATIC);
        put(69, NITRATE_AND_NITRITE_COMPOUNDS_INORGANIC);
        put(70, ACETALS_KETALS_HEMIACETALS_AND_HEMIKETALS);
        put(71, ACRYLATES_AND_ACRYLIC_ACIDS);
        put(72, PHENOLIC_SALTS);
        put(73, QUATERNARY_AMMONIUM_AND_PHOSPHONIUM_SALTS);
        put(74, SULFITE_AND_THIOSULFATE_SALTS);
        put(75, OXIMES);
        put(76, POLYMERIZABLE_COMPOUNDS);
        put(98, NOT_CHEMICALLY_REACTIVE);
        put(99, INSUFFICIENT_INFORMATION_FOR_CLASSIFICATION);
        put(100, WATER_AND_AQUEOUS_SOLUTIONS);
        //put(128, MAT);
        //put(129, REAL);
        //put(130, NAT);
        //put(131, CONST);
    }};

    public static Map<ChemTypes, Set<ChemTypes>> illegalCombos = new HashMap<ChemTypes, Set<ChemTypes>>() {{
        put(ACIDS_STRONG_NON_OXIDIZING, new HashSet<ChemTypes>() {{add(ACIDS_STRONG_NON_OXIDIZING); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ACRYLATES_AND_ACRYLIC_ACIDS); add(ACYL_HALIDES_SULFONYL_HALIDES_AND_CHLOROFORMATES); }});
        put(ACIDS_STRONG_OXIDIZING, new HashSet<ChemTypes>() {{add(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(ACIDS_STRONG_OXIDIZING); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ALDEHYDES); }});
        put(ACIDS_CARBOXYLIC, new HashSet<ChemTypes>() {{add(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC); add(DIAZONIUM_SALTS); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(NITRILES); add(AMIDES_AND_IMIDES); add(KETONES); add(SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC); add(BASES_STRONG); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(PHENOLS_AND_CRESOLS); add(HALOGENATED_ORGANIC_COMPOUNDS); add(METALS_ELEMENTAL_AND_POWDER_ACTIVE); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(ALDEHYDES); add(ALCOHOLS_AND_POLYOLS); add(ACIDS_CARBOXYLIC); add(SALTS_BASIC); add(CHLOROSILANES); }});
        put(ALCOHOLS_AND_POLYOLS, new HashSet<ChemTypes>() {{add(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC); add(AMINES_AROMATIC); add(ACIDS_STRONG_NON_OXIDIZING); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(CYANIDES_INORGANIC); add(ACYL_HALIDES_SULFONYL_HALIDES_AND_CHLOROFORMATES); add(SALTS_ACIDIC); add(BASES_STRONG); add(SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ETHERS); add(ALDEHYDES); add(ACIDS_CARBOXYLIC); add(ALCOHOLS_AND_POLYOLS); add(SALTS_BASIC); add(FLUORINATED_ORGANIC_COMPOUNDS); }});
        put(ALDEHYDES, new HashSet<ChemTypes>() {{add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(AMIDES_AND_IMIDES); }});
        put(AMIDES_AND_IMIDES, new HashSet<ChemTypes>() {{add(HYDROCARBONS_AROMATIC); add(FLUORIDE_SALTS_SOLUBLE); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(PHENOLS_AND_CRESOLS); add(CYANIDES_INORGANIC); add(ALDEHYDES); add(METALS_LESS_REACTIVE); }});
        put(AMINES_PHOSPHINES_AND_PYRIDINES, new HashSet<ChemTypes>() {{add(BASES_STRONG); add(CARBAMATES); add(AMIDES_AND_IMIDES); add(SALTS_ACIDIC); }});
        put(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS, new HashSet<ChemTypes>() {{add(SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC); add(REDUCING_AGENTS_WEAK); add(ALKYNES_WITH_ACETYLENIC_HYDROGEN); add(ACIDS_WEAK); add(ACIDS_CARBOXYLIC); add(CHLOROSILANES); }});
        put(CARBAMATES, new HashSet<ChemTypes>() {{add(HALOGENATING_AGENTS); add(NITRIDES_PHOSPHIDES_CARBIDES_AND_SILICIDES); }});
        put(BASES_STRONG, new HashSet<ChemTypes>() {{add(METALS_ALKALI_VERY_ACTIVE); add(HYDROCARBONS_AROMATIC); add(AMINES_AROMATIC); add(ACIDS_STRONG_NON_OXIDIZING); add(OXIDIZING_AGENTS_WEAK); add(NON_REDOX_ACTIVE_INORGANIC_COMPOUNDS); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(ACIDS_STRONG_OXIDIZING); add(CYANIDES_INORGANIC); add(ACRYLATES_AND_ACRYLIC_ACIDS); add(ANHYDRIDES); add(AMIDES_AND_IMIDES); add(SULFIDES_ORGANIC); add(BASES_STRONG); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(REDUCING_AGENTS_WEAK); add(METALS_ELEMENTAL_AND_POWDER_ACTIVE); add(ETHERS); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(CARBAMATES); add(ALCOHOLS_AND_POLYOLS); add(METALS_LESS_REACTIVE); }});
        put(CYANIDES_INORGANIC, new HashSet<ChemTypes>() {{add(HYDROCARBONS_AROMATIC); add(METALS_ALKALI_VERY_ACTIVE); add(OXIDIZING_AGENTS_WEAK); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(NON_REDOX_ACTIVE_INORGANIC_COMPOUNDS); add(METAL_HYDRIDES_METAL_ALKYLS_METAL_ARYLS_AND_SILANES); add(PEROXIDES_ORGANIC); add(NITRIDES_PHOSPHIDES_CARBIDES_AND_SILICIDES); add(CYANIDES_INORGANIC); add(NITRILES); add(AMIDES_AND_IMIDES); add(KETONES); add(BASES_STRONG); add(CONJUGATED_DIENES); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(HALOGENATING_AGENTS); add(PHENOLS_AND_CRESOLS); add(OXIMES); add(ALDEHYDES); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(CARBAMATES); add(ACIDS_CARBOXYLIC); add(METALS_LESS_REACTIVE); add(CHLOROSILANES); }});
        put(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS, new HashSet<ChemTypes>() {{add(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC); }});
        put(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS, new HashSet<ChemTypes>() {{add(HYDROCARBONS_AROMATIC); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(HALOGENATING_AGENTS); add(ACIDS_STRONG_OXIDIZING); add(ETHERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(AMIDES_AND_IMIDES); }});
        put(ETHERS, new HashSet<ChemTypes>() {{add(HYDROCARBONS_AROMATIC); add(KETONES); add(BASES_STRONG); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(ARYL_HALIDES); add(CYANIDES_INORGANIC); }});
        put(HYDROCARBONS_AROMATIC, new HashSet<ChemTypes>() {{add(ACIDS_STRONG_NON_OXIDIZING); add(FLUORIDE_SALTS_SOLUBLE); add(METAL_HYDRIDES_METAL_ALKYLS_METAL_ARYLS_AND_SILANES); add(NITRILES); add(ANHYDRIDES); add(SULFIDES_INORGANIC); add(KETONES); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(ALDEHYDES); add(ACIDS_CARBOXYLIC); add(HYDROCARBONS_AROMATIC); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(DIAZONIUM_SALTS); add(ACIDS_STRONG_OXIDIZING); add(CYANIDES_INORGANIC); add(ALKYNES_WITH_ACETYLENIC_HYDROGEN); add(AMIDES_AND_IMIDES); add(SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(HALOGENATED_ORGANIC_COMPOUNDS); add(METALS_ELEMENTAL_AND_POWDER_ACTIVE); add(PHENOLS_AND_CRESOLS); add(ORGANOMETALLICS); add(ETHERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(CARBAMATES); add(ALCOHOLS_AND_POLYOLS); }});
        put(HALOGENATED_ORGANIC_COMPOUNDS, new HashSet<>());
        put(ISOCYANATES_AND_ISOTHIOCYANATES, new HashSet<ChemTypes>() {{add(ACIDS_STRONG_NON_OXIDIZING); add(FLUORIDE_SALTS_SOLUBLE); add(REDUCING_AGENTS_STRONG); add(ACETALS_KETALS_HEMIACETALS_AND_HEMIKETALS); add(NITRILES); add(ANHYDRIDES); add(SULFIDES_ORGANIC); add(CONJUGATED_DIENES); add(ACIDS_WEAK); add(ALDEHYDES); add(ACIDS_CARBOXYLIC); add(METALS_ALKALI_VERY_ACTIVE); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(NON_REDOX_ACTIVE_INORGANIC_COMPOUNDS); add(SULFITE_AND_THIOSULFATE_SALTS); add(ACIDS_STRONG_OXIDIZING); add(AMIDES_AND_IMIDES); add(SALTS_ACIDIC); add(SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC); add(BASES_STRONG); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(PHENOLS_AND_CRESOLS); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ETHERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(CARBAMATES); add(METALS_LESS_REACTIVE); }});
        put(KETONES, new HashSet<ChemTypes>() {{add(METALS_ALKALI_VERY_ACTIVE); add(AMINES_AROMATIC); add(PEROXIDES_ORGANIC); add(CYANIDES_INORGANIC); add(ANHYDRIDES); add(SALTS_ACIDIC); add(KETONES); add(SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC); add(BASES_STRONG); add(EPOXIDES); add(HALOGENATED_ORGANIC_COMPOUNDS); add(METALS_ELEMENTAL_AND_POWDER_ACTIVE); add(ALDEHYDES); add(CARBAMATES); add(ACIDS_CARBOXYLIC); add(ALCOHOLS_AND_POLYOLS); add(CARBONATE_SALTS); }});
        put(SULFIDES_ORGANIC, new HashSet<ChemTypes>() {{add(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC); add(ACIDS_STRONG_NON_OXIDIZING); add(METAL_HYDRIDES_METAL_ALKYLS_METAL_ARYLS_AND_SILANES); add(NITRILES); add(SULFIDES_INORGANIC); add(KETONES); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(ALDEHYDES); add(SALTS_BASIC); add(ACIDS_CARBOXYLIC); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(QUATERNARY_AMMONIUM_AND_PHOSPHONIUM_SALTS); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(NITRIDES_PHOSPHIDES_CARBIDES_AND_SILICIDES); add(ACIDS_STRONG_OXIDIZING); add(AMIDES_AND_IMIDES); add(SALTS_ACIDIC); add(BASES_STRONG); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(PHENOLS_AND_CRESOLS); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ETHERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(CARBAMATES); add(ALCOHOLS_AND_POLYOLS); add(METALS_LESS_REACTIVE); }});
        put(METALS_ALKALI_VERY_ACTIVE, new HashSet<ChemTypes>() {{add(SULFIDES_INORGANIC); add(AMINES_PHOSPHINES_AND_PYRIDINES); }});
        put(METALS_ELEMENTAL_AND_POWDER_ACTIVE, new HashSet<>());
        put(METALS_LESS_REACTIVE, new HashSet<ChemTypes>() {{add(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC); add(ACIDS_STRONG_NON_OXIDIZING); add(METAL_HYDRIDES_METAL_ALKYLS_METAL_ARYLS_AND_SILANES); add(PEROXIDES_ORGANIC); add(NITRILES); add(KETONES); add(ALDEHYDES); add(ACIDS_CARBOXYLIC); add(FLUORINATED_ORGANIC_COMPOUNDS); add(METALS_ALKALI_VERY_ACTIVE); add(HYDROCARBONS_AROMATIC); add(DIAZONIUM_SALTS); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(ACIDS_STRONG_OXIDIZING); add(AMIDES_AND_IMIDES); add(SALTS_ACIDIC); add(BASES_STRONG); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(REDUCING_AGENTS_WEAK); add(PHENOLS_AND_CRESOLS); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ETHERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(CARBAMATES); add(ALCOHOLS_AND_POLYOLS); add(METALS_LESS_REACTIVE); }});
        put(DIAZONIUM_SALTS, new HashSet<>());
        put(NITRILES, new HashSet<ChemTypes>() {{add(OXIDIZING_AGENTS_STRONG); add(ACIDS_STRONG_NON_OXIDIZING); add(METAL_HYDRIDES_METAL_ALKYLS_METAL_ARYLS_AND_SILANES); add(PEROXIDES_ORGANIC); add(SILOXANES); add(NITRILES); add(SULFIDES_ORGANIC); add(KETONES); add(HYDROCARBONS_AROMATIC); add(METALS_ALKALI_VERY_ACTIVE); add(DIAZONIUM_SALTS); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(NON_REDOX_ACTIVE_INORGANIC_COMPOUNDS); add(SULFITE_AND_THIOSULFATE_SALTS); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(ACIDS_STRONG_OXIDIZING); add(AMIDES_AND_IMIDES); add(SALTS_ACIDIC); add(SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC); add(BASES_STRONG); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(HALOGENATED_ORGANIC_COMPOUNDS); add(PHENOLS_AND_CRESOLS); add(ETHERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(METALS_LESS_REACTIVE); add(ALCOHOLS_AND_POLYOLS); }});
        put(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC, new HashSet<ChemTypes>() {{add(METALS_ELEMENTAL_AND_POWDER_ACTIVE); }});
        put(HYDROCARBONS_ALIPHATIC_UNSATURATED, new HashSet<>());
        put(HYDROCARBONS_ALIPHATIC_SATURATED, new HashSet<ChemTypes>() {{add(HYDROCARBONS_AROMATIC); add(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC); add(OXIDIZING_AGENTS_WEAK); add(REDUCING_AGENTS_STRONG); add(PEROXIDES_ORGANIC); add(ACIDS_STRONG_OXIDIZING); add(ALDEHYDES); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(SALTS_ACIDIC); }});
        put(PEROXIDES_ORGANIC, new HashSet<ChemTypes>() {{add(HYDROCARBONS_AROMATIC); add(ACIDS_STRONG_NON_OXIDIZING); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(ACIDS_STRONG_OXIDIZING); add(CYANIDES_INORGANIC); add(ANHYDRIDES); add(AMIDES_AND_IMIDES); add(BASES_STRONG); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ETHERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(CARBAMATES); add(SALTS_BASIC); add(METALS_LESS_REACTIVE); add(ACIDS_CARBOXYLIC); }});
        put(PHENOLS_AND_CRESOLS, new HashSet<ChemTypes>() {{add(METALS_ALKALI_VERY_ACTIVE); add(SULFIDES_ORGANIC); add(ACIDS_STRONG_NON_OXIDIZING); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(ACIDS_STRONG_OXIDIZING); add(ETHERS); add(ALKYNES_WITH_NO_ACETYLENIC_HYDROGEN); add(ALDEHYDES); add(ACIDS_CARBOXYLIC); add(SALTS_ACIDIC); }});
        put(SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC, new HashSet<ChemTypes>() {{add(ACIDS_STRONG_NON_OXIDIZING); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(ACIDS_CARBOXYLIC); }});
        put(SULFIDES_INORGANIC, new HashSet<>());
        put(EPOXIDES, new HashSet<ChemTypes>() {{add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(ACIDS_STRONG_OXIDIZING); add(ETHERS); add(NITRILES); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(ACIDS_CARBOXYLIC); add(ALCOHOLS_AND_POLYOLS); }});
        put(METAL_HYDRIDES_METAL_ALKYLS_METAL_ARYLS_AND_SILANES, new HashSet<ChemTypes>() {{add(ACIDS_STRONG_OXIDIZING); add(ALDEHYDES); }});
        put(ANHYDRIDES, new HashSet<ChemTypes>() {{add(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC); add(ACIDS_STRONG_NON_OXIDIZING); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(ARYL_HALIDES); add(CYANIDES_INORGANIC); add(NITRILES); add(ANHYDRIDES); add(AMIDES_AND_IMIDES); add(SULFIDES_ORGANIC); add(BASES_STRONG); add(HALOGENATING_AGENTS); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(METALS_ELEMENTAL_AND_POWDER_ACTIVE); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ETHERS); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(CARBAMATES); add(ALCOHOLS_AND_POLYOLS); }});
        put(SALTS_ACIDIC, new HashSet<>());
        put(SALTS_BASIC, new HashSet<ChemTypes>() {{add(BASES_STRONG); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(ARYL_HALIDES); add(CYANIDES_INORGANIC); add(ACIDS_WEAK); }});
        put(ACYL_HALIDES_SULFONYL_HALIDES_AND_CHLOROFORMATES, new HashSet<ChemTypes>() {{add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(DIAZONIUM_SALTS); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(NITRIDES_PHOSPHIDES_CARBIDES_AND_SILICIDES); add(ACIDS_STRONG_OXIDIZING); add(KETONES); add(CONJUGATED_DIENES); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(ETHERS); add(ACIDS_WEAK); add(CARBAMATES); add(ALCOHOLS_AND_POLYOLS); add(ACIDS_CARBOXYLIC); add(CARBONATE_SALTS); }});
        put(ORGANOMETALLICS, new HashSet<ChemTypes>() {{add(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC); add(METALS_ALKALI_VERY_ACTIVE); add(KETONES); add(DIAZONIUM_SALTS); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(REDUCING_AGENTS_WEAK); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(CARBAMATES); add(ACYL_HALIDES_SULFONYL_HALIDES_AND_CHLOROFORMATES); }});
        put(OXIDIZING_AGENTS_STRONG, new HashSet<ChemTypes>() {{add(REDUCING_AGENTS_WEAK); add(CYANIDES_INORGANIC); }});
        put(REDUCING_AGENTS_STRONG, new HashSet<ChemTypes>() {{add(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC); add(REDUCING_AGENTS_STRONG); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(METAL_HYDRIDES_METAL_ALKYLS_METAL_ARYLS_AND_SILANES); add(NITRIDES_PHOSPHIDES_CARBIDES_AND_SILICIDES); add(ACIDS_STRONG_OXIDIZING); add(CYANIDES_INORGANIC); add(NITRILES); add(ANHYDRIDES); add(AMIDES_AND_IMIDES); add(SALTS_ACIDIC); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(REDUCING_AGENTS_WEAK); add(PHENOLS_AND_CRESOLS); add(ETHERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(CARBAMATES); add(ACIDS_CARBOXYLIC); add(METALS_LESS_REACTIVE); add(ALCOHOLS_AND_POLYOLS); }});
        put(NON_REDOX_ACTIVE_INORGANIC_COMPOUNDS, new HashSet<ChemTypes>() {{add(OXIDIZING_AGENTS_STRONG); add(FLUORIDE_SALTS_SOLUBLE); add(ACIDS_STRONG_NON_OXIDIZING); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(METAL_HYDRIDES_METAL_ALKYLS_METAL_ARYLS_AND_SILANES); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(ACIDS_STRONG_OXIDIZING); add(NITRIDES_PHOSPHIDES_CARBIDES_AND_SILICIDES); add(AMIDES_AND_IMIDES); add(SULFIDES_INORGANIC); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(HALOGENATING_AGENTS); add(EPOXIDES); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ALDEHYDES); add(CARBAMATES); add(SALTS_BASIC); add(FLUORINATED_ORGANIC_COMPOUNDS); add(METALS_LESS_REACTIVE); add(ACIDS_CARBOXYLIC); add(ALCOHOLS_AND_POLYOLS); add(CHLOROSILANES); }});
        put(FLUORINATED_ORGANIC_COMPOUNDS, new HashSet<ChemTypes>() {{add(ACIDS_STRONG_NON_OXIDIZING); add(SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC); add(KETONES); add(DIAZONIUM_SALTS); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(ACIDS_STRONG_OXIDIZING); add(NITRIDES_PHOSPHIDES_CARBIDES_AND_SILICIDES); add(ALCOHOLS_AND_POLYOLS); add(SALTS_BASIC); }});
        put(FLUORIDE_SALTS_SOLUBLE, new HashSet<ChemTypes>() {{add(ACIDS_STRONG_NON_OXIDIZING); add(OXIDIZING_AGENTS_WEAK); add(FLUORIDE_SALTS_SOLUBLE); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(DIAZONIUM_SALTS); add(NON_REDOX_ACTIVE_INORGANIC_COMPOUNDS); add(CYANIDES_INORGANIC); add(NITRILES); add(ACYL_HALIDES_SULFONYL_HALIDES_AND_CHLOROFORMATES); add(AMIDES_AND_IMIDES); add(SULFIDES_INORGANIC); add(BASES_STRONG); add(KETONES); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(ALDEHYDES); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(ALCOHOLS_AND_POLYOLS); add(ACIDS_CARBOXYLIC); add(CARBONATE_SALTS); }});
        put(OXIDIZING_AGENTS_WEAK, new HashSet<ChemTypes>() {{add(HYDROCARBONS_AROMATIC); add(SULFIDES_INORGANIC); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ACIDS_STRONG_OXIDIZING); add(ETHERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(METALS_LESS_REACTIVE); add(ALCOHOLS_AND_POLYOLS); add(CARBONATE_SALTS); }});
        put(REDUCING_AGENTS_WEAK, new HashSet<ChemTypes>() {{add(ACIDS_STRONG_NON_OXIDIZING); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(ORGANOMETALLICS); add(ETHERS); add(NITRILES); add(ALKYNES_WITH_NO_ACETYLENIC_HYDROGEN); add(ALDEHYDES); add(ALCOHOLS_AND_POLYOLS); add(AMIDES_AND_IMIDES); }});
        put(NITRIDES_PHOSPHIDES_CARBIDES_AND_SILICIDES, new HashSet<ChemTypes>() {{add(METALS_ALKALI_VERY_ACTIVE); add(SULFIDES_ORGANIC); add(ACIDS_STRONG_NON_OXIDIZING); add(BASES_STRONG); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(ACIDS_WEAK); add(CARBAMATES); add(ALCOHOLS_AND_POLYOLS); add(ACYL_HALIDES_SULFONYL_HALIDES_AND_CHLOROFORMATES); add(SALTS_BASIC); add(ACIDS_CARBOXYLIC); }});
        put(CHLOROSILANES, new HashSet<ChemTypes>() {{add(METALS_ALKALI_VERY_ACTIVE); add(OXIDIZING_AGENTS_STRONG); add(ACIDS_STRONG_NON_OXIDIZING); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(DIAZONIUM_SALTS); add(PEROXIDES_ORGANIC); add(ACIDS_STRONG_OXIDIZING); add(AMIDES_AND_IMIDES); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ETHERS); add(ACIDS_WEAK); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(ALDEHYDES); add(SALTS_BASIC); add(ACIDS_CARBOXYLIC); add(METALS_LESS_REACTIVE); add(CHLOROSILANES); }});
        put(SILOXANES, new HashSet<ChemTypes>() {{add(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC); add(ACIDS_STRONG_NON_OXIDIZING); add(REDUCING_AGENTS_STRONG); add(NITRILES); add(ANHYDRIDES); add(SULFIDES_INORGANIC); add(SULFIDES_ORGANIC); add(KETONES); add(CONJUGATED_DIENES); add(HALOGENATING_AGENTS); add(EPOXIDES); add(ALDEHYDES); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(ACIDS_CARBOXYLIC); add(SALTS_BASIC); add(HYDROCARBONS_AROMATIC); add(METALS_ALKALI_VERY_ACTIVE); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(ACIDS_STRONG_OXIDIZING); add(CYANIDES_INORGANIC); add(ALKYNES_WITH_ACETYLENIC_HYDROGEN); add(SALTS_ACIDIC); add(AMIDES_AND_IMIDES); add(BASES_STRONG); add(SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(HALOGENATED_ORGANIC_COMPOUNDS); add(METALS_ELEMENTAL_AND_POWDER_ACTIVE); add(ETHERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(CARBAMATES); add(ALCOHOLS_AND_POLYOLS); add(METALS_LESS_REACTIVE); }});
        put(HALOGENATING_AGENTS, new HashSet<ChemTypes>() {{add(METALS_ALKALI_VERY_ACTIVE); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(REDUCING_AGENTS_WEAK); }});
        put(ACIDS_WEAK, new HashSet<ChemTypes>() {{add(PEROXIDES_ORGANIC); add(ALKYNES_WITH_ACETYLENIC_HYDROGEN); }});
        put(BASES_WEAK, new HashSet<ChemTypes>() {{add(FLUORIDE_SALTS_SOLUBLE); add(ACIDS_STRONG_NON_OXIDIZING); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); }});
        put(CARBONATE_SALTS, new HashSet<ChemTypes>() {{add(ORGANOMETALLICS); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ALCOHOLS_AND_POLYOLS); }});
        put(ALKYNES_WITH_ACETYLENIC_HYDROGEN, new HashSet<ChemTypes>() {{add(METALS_ALKALI_VERY_ACTIVE); add(HYDROCARBONS_AROMATIC); add(ACIDS_STRONG_NON_OXIDIZING); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(NON_REDOX_ACTIVE_INORGANIC_COMPOUNDS); add(PEROXIDES_ORGANIC); add(ACIDS_STRONG_OXIDIZING); add(BASES_WEAK); add(ACYL_HALIDES_SULFONYL_HALIDES_AND_CHLOROFORMATES); add(SALTS_ACIDIC); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(METALS_ELEMENTAL_AND_POWDER_ACTIVE); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(SALTS_BASIC); add(ACIDS_CARBOXYLIC); }});
        put(ALKYNES_WITH_NO_ACETYLENIC_HYDROGEN, new HashSet<ChemTypes>() {{add(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC); add(ACIDS_STRONG_NON_OXIDIZING); add(REDUCING_AGENTS_WEAK); add(ARYL_HALIDES); add(EPOXIDES); add(CYANIDES_INORGANIC); add(ETHERS); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); }});
        put(CONJUGATED_DIENES, new HashSet<>());
        put(ARYL_HALIDES, new HashSet<ChemTypes>() {{add(DIAZONIUM_SALTS); add(HALOGENATED_ORGANIC_COMPOUNDS); add(PHENOLS_AND_CRESOLS); add(AMIDES_AND_IMIDES); }});
        put(AMINES_AROMATIC, new HashSet<ChemTypes>() {{add(BASES_STRONG); }});
        put(NITRATE_AND_NITRITE_COMPOUNDS_INORGANIC, new HashSet<>());
        put(ACETALS_KETALS_HEMIACETALS_AND_HEMIKETALS, new HashSet<ChemTypes>() {{add(HYDROCARBONS_AROMATIC); add(ACIDS_STRONG_NON_OXIDIZING); add(EPOXIDES); add(AMIDES_AND_IMIDES); }});
        put(ACRYLATES_AND_ACRYLIC_ACIDS, new HashSet<ChemTypes>() {{add(ACETALS_KETALS_HEMIACETALS_AND_HEMIKETALS); add(CYANIDES_INORGANIC); add(ALDEHYDES); }});
        put(PHENOLIC_SALTS, new HashSet<ChemTypes>() {{add(BASES_STRONG); add(SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(METAL_HYDRIDES_METAL_ALKYLS_METAL_ARYLS_AND_SILANES); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(HALOGENATED_ORGANIC_COMPOUNDS); add(PHENOLS_AND_CRESOLS); add(ETHERS); add(NITRILES); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(CARBAMATES); add(CARBONATE_SALTS); }});
        put(QUATERNARY_AMMONIUM_AND_PHOSPHONIUM_SALTS, new HashSet<ChemTypes>() {{add(METALS_ALKALI_VERY_ACTIVE); add(ACIDS_STRONG_NON_OXIDIZING); add(FLUORIDE_SALTS_SOLUBLE); add(DIAZONIUM_SALTS); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(METAL_HYDRIDES_METAL_ALKYLS_METAL_ARYLS_AND_SILANES); add(NON_REDOX_ACTIVE_INORGANIC_COMPOUNDS); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(CYANIDES_INORGANIC); add(NITRILES); add(SULFIDES_INORGANIC); add(SULFIDES_ORGANIC); add(BASES_STRONG); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(EPOXIDES); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ETHERS); add(ALDEHYDES); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(ALCOHOLS_AND_POLYOLS); add(FLUORINATED_ORGANIC_COMPOUNDS); add(ACIDS_CARBOXYLIC); }});
        put(SULFITE_AND_THIOSULFATE_SALTS, new HashSet<ChemTypes>() {{add(ACIDS_STRONG_NON_OXIDIZING); add(METAL_HYDRIDES_METAL_ALKYLS_METAL_ARYLS_AND_SILANES); add(ACYL_HALIDES_SULFONYL_HALIDES_AND_CHLOROFORMATES); add(SULFIDES_ORGANIC); add(CONJUGATED_DIENES); add(EPOXIDES); add(ALDEHYDES); add(ACIDS_CARBOXYLIC); add(FLUORINATED_ORGANIC_COMPOUNDS); add(METALS_ALKALI_VERY_ACTIVE); add(DIAZONIUM_SALTS); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(NON_REDOX_ACTIVE_INORGANIC_COMPOUNDS); add(SULFITE_AND_THIOSULFATE_SALTS); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(ACIDS_STRONG_OXIDIZING); add(NITRIDES_PHOSPHIDES_CARBIDES_AND_SILICIDES); add(CYANIDES_INORGANIC); add(AMIDES_AND_IMIDES); add(SALTS_ACIDIC); add(BASES_STRONG); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ETHERS); add(ALKYNES_WITH_NO_ACETYLENIC_HYDROGEN); add(ALCOHOLS_AND_POLYOLS); add(METALS_LESS_REACTIVE); }});
        put(OXIMES, new HashSet<ChemTypes>() {{add(OXIDIZING_AGENTS_STRONG); add(SULFIDES_ORGANIC); add(EPOXIDES); add(CYANIDES_INORGANIC); add(ACIDS_WEAK); add(ALDEHYDES); add(SALTS_BASIC); add(ACIDS_CARBOXYLIC); add(ALCOHOLS_AND_POLYOLS); add(AMIDES_AND_IMIDES); }});
        put(POLYMERIZABLE_COMPOUNDS, new HashSet<ChemTypes>() {{add(ACIDS_STRONG_NON_OXIDIZING); add(DIAZONIUM_SALTS); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(HALOGENATED_ORGANIC_COMPOUNDS); add(ACIDS_STRONG_OXIDIZING); add(ETHERS); add(ALDEHYDES); add(METALS_LESS_REACTIVE); add(ALCOHOLS_AND_POLYOLS); add(AMIDES_AND_IMIDES); }});
        put(NOT_CHEMICALLY_REACTIVE, new HashSet<ChemTypes>() {{add(SULFIDES_INORGANIC); add(SULFIDES_ORGANIC); add(ACIDS_STRONG_NON_OXIDIZING); add(KETONES); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(ACIDS_STRONG_OXIDIZING); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(CARBAMATES); add(SALTS_BASIC); add(METALS_LESS_REACTIVE); }});
        put(INSUFFICIENT_INFORMATION_FOR_CLASSIFICATION, new HashSet<ChemTypes>() {{add(NITRO_NITROSO_NITRATE_AND_NITRITE_COMPOUNDS_ORGANIC); add(OXIDIZING_AGENTS_STRONG); add(ACIDS_STRONG_NON_OXIDIZING); add(PEROXIDES_ORGANIC); add(SILOXANES); add(ANHYDRIDES); add(ACYL_HALIDES_SULFONYL_HALIDES_AND_CHLOROFORMATES); add(SULFIDES_ORGANIC); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(SALTS_BASIC); add(ACIDS_CARBOXYLIC); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(HYDROCARBONS_ALIPHATIC_UNSATURATED); add(ACIDS_STRONG_OXIDIZING); add(AMIDES_AND_IMIDES); add(NITRATE_AND_NITRITE_COMPOUNDS_INORGANIC); add(BASES_STRONG); add(SULFONATES_PHOSPHONATES_AND_THIOPHOSPHONATES_ORGANIC); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(REDUCING_AGENTS_WEAK); add(HALOGENATED_ORGANIC_COMPOUNDS); add(METALS_ELEMENTAL_AND_POWDER_ACTIVE); add(ETHERS); add(AMINES_PHOSPHINES_AND_PYRIDINES); add(CARBAMATES); add(ALCOHOLS_AND_POLYOLS); }});
        put(WATER_AND_AQUEOUS_SOLUTIONS, new HashSet<ChemTypes>() {{add(ACIDS_STRONG_NON_OXIDIZING); add(ARYL_HALIDES); add(PEROXIDES_ORGANIC); add(ANHYDRIDES); add(SULFIDES_ORGANIC); add(KETONES); add(EPOXIDES); add(ESTERS_SULFATE_ESTERS_PHOSPHATE_ESTERS_THIOPHOSPHATE_ESTERS_AND_BORATE_ESTERS); add(ACIDS_WEAK); add(ALDEHYDES); add(SALTS_BASIC); add(ACIDS_CARBOXYLIC); add(CARBONATE_SALTS); add(METALS_ALKALI_VERY_ACTIVE); add(AZO_DIAZO_AZIDO_HYDRAZINE_AND_AZIDE_COMPOUNDS); add(DIAZONIUM_SALTS); add(HYDROCARBONS_ALIPHATIC_SATURATED); add(ACIDS_STRONG_OXIDIZING); add(ACRYLATES_AND_ACRYLIC_ACIDS); add(CYANIDES_INORGANIC); add(ALKYNES_WITH_ACETYLENIC_HYDROGEN); add(AMIDES_AND_IMIDES); add(BASES_STRONG); add(THIOCARBAMATE_ESTERS_AND_SALTS_DITHIOCARBAMATE_ESTERS_AND_SALTS); add(ISOCYANATES_AND_ISOTHIOCYANATES); add(HALOGENATED_ORGANIC_COMPOUNDS); add(METALS_ELEMENTAL_AND_POWDER_ACTIVE); add(ETHERS); add(CARBAMATES); add(ALCOHOLS_AND_POLYOLS); }});
    }};

    private int value;
    ChemTypes(int value) {
        this.value = value;
    }

    public int getValue() {
        return this.value;
    }

    public static ChemTypes getTypeFromId(int id) {
        return integerChemTypesMap.get(id);
    }

    public static Map<Integer, ChemTypes> getIntegerChemTypesMap() {
        return integerChemTypesMap;
    }
}
