//
// Generated by JTB 1.3.2
//

package parser.ast;

import parser.visitor.GJNoArguVisitor;
import parser.visitor.GJVisitor;
import parser.visitor.GJVoidVisitor;
import parser.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> Module()
 * f1 -> Stationary()
 * f2 -> Manifest()
 * f3 -> <INSTRUCTIONS>
 * f4 -> Instruction()
 * f5 -> <EOF>
 */
public class BSProgram implements Node {
    public Module f0;
    public Stationary f1;
    public Manifest f2;
    public NodeToken f3;
    public Instruction f4;
    public NodeToken f5;

    public BSProgram(Module n0, Stationary n1, Manifest n2, NodeToken n3, Instruction n4, NodeToken n5) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
        f3 = n3;
        f4 = n4;
        f5 = n5;
    }

    public BSProgram(Module n0, Stationary n1, Manifest n2, Instruction n3) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
        f3 = new NodeToken("instructions");
        f4 = n3;
        f5 = new NodeToken("");
    }

    public void accept(Visitor v) {
        v.visit(this);
    }

    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

