//
// Generated by JTB 1.3.2
//

package parser.ast;

import parser.visitor.GJNoArguVisitor;
import parser.visitor.GJVisitor;
import parser.visitor.GJVoidVisitor;
import parser.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> <DRAIN>
 * f1 -> PrimaryExpression()
 */
public class DrainInstruction implements Node {
    public NodeToken f0;
    public PrimaryExpression f1;

    public DrainInstruction(NodeToken n0, PrimaryExpression n1) {
        f0 = n0;
        f1 = n1;
    }

    public DrainInstruction(PrimaryExpression n0) {
        f0 = new NodeToken("drain");
        f1 = n0;
    }

    public void accept(Visitor v) {
        v.visit(this);
    }

    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

