//
// Generated by JTB 1.3.2
//

package parser.ast;

import parser.visitor.GJNoArguVisitor;
import parser.visitor.GJVisitor;
import parser.visitor.GJVoidVisitor;
import parser.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> <ELSE_IF>
 * f1 -> <LPAREN>
 * f2 -> Conditional()
 * f3 -> <RPAREN>
 * f4 -> <LBRACE>
 * f5 -> ( Statements() )+
 * f6 -> <RBRACE>
 */
public class ElseIfBranchStatement implements Node {
    public NodeToken f0;
    public NodeToken f1;
    public Conditional f2;
    public NodeToken f3;
    public NodeToken f4;
    public NodeList f5;
    public NodeToken f6;

    public ElseIfBranchStatement(NodeToken n0, NodeToken n1, Conditional n2, NodeToken n3, NodeToken n4, NodeList n5, NodeToken n6) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
        f3 = n3;
        f4 = n4;
        f5 = n5;
        f6 = n6;
    }

    public ElseIfBranchStatement(Conditional n0, NodeList n1) {
        f0 = new NodeToken("else if");
        f1 = new NodeToken("(");
        f2 = n0;
        f3 = new NodeToken(")");
        f4 = new NodeToken("{");
        f5 = n1;
        f6 = new NodeToken("}");
    }

    public void accept(Visitor v) {
        v.visit(this);
    }

    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

