//
// Generated by JTB 1.3.2
//

package parser.ast;

import parser.visitor.GJNoArguVisitor;
import parser.visitor.GJVisitor;
import parser.visitor.GJVoidVisitor;
import parser.visitor.Visitor;

/**
 * Grammar production:
 * f0 -> <MIX>
 * f1 -> ( VolumeUnit() <OF> )?
 * f2 -> PrimaryExpression()
 * f3 -> <WITH>
 * f4 -> ( VolumeUnit() <OF> )?
 * f5 -> PrimaryExpression()
 * f6 -> ( <FOR> TimeUnit() )?
 */
public class MixStatement implements Node {
    public NodeToken f0;
    public NodeOptional f1;
    public PrimaryExpression f2;
    public NodeToken f3;
    public NodeOptional f4;
    public PrimaryExpression f5;
    public NodeOptional f6;

    public MixStatement(NodeToken n0, NodeOptional n1, PrimaryExpression n2, NodeToken n3, NodeOptional n4, PrimaryExpression n5, NodeOptional n6) {
        f0 = n0;
        f1 = n1;
        f2 = n2;
        f3 = n3;
        f4 = n4;
        f5 = n5;
        f6 = n6;
    }

    public MixStatement(NodeOptional n0, PrimaryExpression n1, NodeOptional n2, PrimaryExpression n3, NodeOptional n4) {
        f0 = new NodeToken("mix");
        f1 = n0;
        f2 = n1;
        f3 = new NodeToken("with");
        f4 = n2;
        f5 = n3;
        f6 = n4;
    }

    public void accept(Visitor v) {
        v.visit(this);
    }

    public <R, A> R accept(GJVisitor<R, A> v, A argu) {
        return v.visit(this, argu);
    }

    public <R> R accept(GJNoArguVisitor<R> v) {
        return v.visit(this);
    }

    public <A> void accept(GJVoidVisitor<A> v, A argu) {
        v.visit(this, argu);
    }
}

