//
// Generated by JTB 1.3.2
//

package parser.ast;

import parser.visitor.*;

/**
 * Grammar production:
 * f0 -> <STATIONARY>
 * f1 -> ( TypingList() )?
 * f2 -> PrimaryExpression()
 */
public class Stationary implements Node {
   public NodeToken f0;
   public NodeOptional f1;
   public PrimaryExpression f2;

   public Stationary(NodeToken n0, NodeOptional n1, PrimaryExpression n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public Stationary(NodeOptional n0, PrimaryExpression n1) {
      f0 = new NodeToken("stationary");
      f1 = n0;
      f2 = n1;
   }

   public void accept(Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

