module test
stationary test2
manifest mat chemical1
manifest chemical2

instructions

function doThis(mat chem) : mat {
    a = mix chemical1 with chemical2
    b = mix a with chemical2 for 30
    nat c = detect something on somethingelse
}

function doThis2(mat chem, mat chem3, chem4) {
    a = mix chem with chem3
    return mix a with b
}

doThis(a)

aa = doThis(a)

aaa = mix chemical1 with chemical2

if (1 < 2) {
    a= mix b with c
} else if (2 < 1) {
    a = mix c with d
} else {
    c = mix d with f
}

repeat 5 times {
    a = mix a with b
}

b = mix a with chemical2 for 30
c = mix b with x
heat c at 49 for 3
heat ca at 34

x = split xx into 4
mat x = split xx into 2