module test
stationary test2
manifest mat chemical1
manifest chemical2

functions

function doThis(mat chem) : mat {
    drain chem
    return b
}

function doThis2(mat chem, mat chem3, chem4) {
    drain chem3
    a = mix chem with chem3
    b = mix a with chem4
    repeat 4 times {
        drain a
        drain chem
    }
    return b
}

instructions

awesome = mix test2 with chemical1
a = doThis2(chemical1, chemical2, awesome)