//
// Generated by JTB 1.3.2
//

package parser.visitor;
import parser.ast.*;
import java.util.*;

/**
 * All GJ visitors must implement this interface.
 */

public interface GJVisitor<R,A> {

   //
   // GJ Auto class visitors
   //

   public R visit(NodeList n, A argu);
   public R visit(NodeListOptional n, A argu);
   public R visit(NodeOptional n, A argu);
   public R visit(NodeSequence n, A argu);
   public R visit(NodeToken n, A argu);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> Stationary()
    * f1 -> Manifest()
    * f2 -> <INSTRUCTIONS>
    * f3 -> Instruction()
    * f4 -> <EOF>
    */
   public R visit(BSProgram n, A argu);

   /**
    * f0 -> <STATIONARY>
    * f1 -> Identifier()
    */
   public R visit(Stationary n, A argu);

   /**
    * f0 -> <MANIFEST>
    * f1 -> Identifier()
    */
   public R visit(Manifest n, A argu);

   /**
    * f0 -> Instruction()
    *       | BranchStatement()
    *       | WhileStatement()
    */
   public R visit(Statement n, A argu);

   /**
    * f0 -> MixStatement()
    *       | SplitStatement()
    *       | DrainStatement()
    *       | HeatStatement()
    *       | DetectStatement()
    *       | RepeatStatement()
    *       | AssignmentStatement()
    */
   public R visit(Instruction n, A argu);

   /**
    * f0 -> <FUNCTION>
    * f1 -> Identifier()
    * f2 -> <LPAREN>
    * f3 -> FormalParameterList()
    * f4 -> <RPAREN>
    * f5 -> ( <COLON> ( TypingList() )* )?
    * f6 -> <LBRACE>
    * f7 -> Statement()
    * f8 -> <LBRACE>
    */
   public R visit(Function n, A argu);

   /**
    * f0 -> Type()
    * f1 -> ( TypingRest() )*
    */
   public R visit(TypingList n, A argu);

   /**
    * f0 -> <COMMA>
    * f1 -> Type()
    */
   public R visit(TypingRest n, A argu);

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu);

   /**
    * f0 -> TypingList()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu);

   /**
    * f0 -> <COMMA>
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu);

   /**
    * f0 -> <MIX> PrimaryExpression() <WITH> PrimaryExpression()
    *       | <FOR> IntegerLiteral()
    */
   public R visit(MixStatement n, A argu);

   /**
    * f0 -> <SPLIT>
    * f1 -> PrimaryExpression()
    * f2 -> <INTO>
    * f3 -> PrimaryExpression()
    */
   public R visit(SplitStatement n, A argu);

   /**
    * f0 -> <DRAIN>
    * f1 -> PrimaryExpression()
    */
   public R visit(DrainStatement n, A argu);

   /**
    * f0 -> <HEAT> PrimaryExpression() <AT> IntegerLiteral()
    *       | <FOR> IntegerLiteral()
    */
   public R visit(HeatStatement n, A argu);

   /**
    * f0 -> <DETECT> Identifier() <ON> PrimaryExpression()
    *       | <FOR> <INTEGER_LITERAL>
    */
   public R visit(DetectStatement n, A argu);

   /**
    * f0 -> WhileStatement()
    */
   public R visit(RepeatStatement n, A argu);

   /**
    * f0 -> ( TypingList() )*
    * f1 -> Identifier()
    * f2 -> <ASSIGN>
    * f3 -> Expression()
    */
   public R visit(AssignmentStatement n, A argu);

   /**
    * f0 -> MatLiteral()
    *       | NatLiteral()
    *       | RealLiteral()
    */
   public R visit(Type n, A argu);

   /**
    * f0 -> <IF> <LPAREN> Expression() <RPAREN> <LBRACE> Statement() <RBRACE>
    *       | <ELSE_IF> <LPAREN> Expression() <RPAREN> <LBRACE> Statement() <RBRACE>
    *       | <ELSE> <LBRACE> Statement() <RBRACE>
    */
   public R visit(BranchStatement n, A argu);

   /**
    * f0 -> <REPEAT>
    * f1 -> IntegerLiteral()
    * f2 -> <TIMES>
    * f3 -> <LBRACE>
    * f4 -> Statement()
    * f5 -> <RBRACE>
    */
   public R visit(WhileStatement n, A argu);

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ParenthesisExpression()
    */
   public R visit(PrimaryExpression n, A argu);

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu);

   /**
    * f0 -> <NAT>
    */
   public R visit(NatLiteral n, A argu);

   /**
    * f0 -> <MAT>
    */
   public R visit(MatLiteral n, A argu);

   /**
    * f0 -> <REAL>
    */
   public R visit(RealLiteral n, A argu);

   /**
    * f0 -> <TRUE>
    */
   public R visit(TrueLiteral n, A argu);

   /**
    * f0 -> <FALSE>
    */
   public R visit(FalseLiteral n, A argu);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu);

   /**
    * f0 -> AndExpression()
    *       | LessThanExpression()
    *       | LessThanEqualExpression()
    *       | GreaterThanExpression()
    *       | GreaterThanEqualExpression()
    *       | NotEqualExpression()
    *       | EqualityExpression()
    *       | OrExpression()
    *       | PlusExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> <AND>
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> <LESSTHAN>
    * f2 -> PrimaryExpression()
    */
   public R visit(LessThanExpression n, A argu);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> <LESSTHANEQUAL>
    * f2 -> PrimaryExpression()
    */
   public R visit(LessThanEqualExpression n, A argu);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> <GREATERTHAN>
    * f2 -> PrimaryExpression()
    */
   public R visit(GreaterThanExpression n, A argu);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> <GREATERTHANEQUAL>
    * f2 -> PrimaryExpression()
    */
   public R visit(GreaterThanEqualExpression n, A argu);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> <NOTEQUAL>
    * f2 -> PrimaryExpression()
    */
   public R visit(NotEqualExpression n, A argu);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> <OR>
    * f2 -> PrimaryExpression()
    */
   public R visit(EqualityExpression n, A argu);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> <LESSTHAN>
    * f2 -> PrimaryExpression()
    */
   public R visit(OrExpression n, A argu);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> <ADD>
    * f2 -> PrimaryExpression()
    */
   public R visit(PlusExpression n, A argu);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> <MINUS>
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu);

   /**
    * f0 -> PrimaryExpression()
    * f1 -> <MULTIPLY>
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu);

   /**
    * f0 -> <BANG>
    * f1 -> Expression()
    */
   public R visit(NotExpression n, A argu);

   /**
    * f0 -> <LPAREN>
    * f1 -> Expression()
    * f2 -> <RPAREN>
    */
   public R visit(ParenthesisExpression n, A argu);

}
