//
// Generated by JTB 1.3.2
//

package parser.visitor;

import parser.ast.AndExpression;
import parser.ast.AssignmentStatement;
import parser.ast.BSProgram;
import parser.ast.BranchStatement;
import parser.ast.DetectStatement;
import parser.ast.DrainStatement;
import parser.ast.EqualityExpression;
import parser.ast.Expression;
import parser.ast.FalseLiteral;
import parser.ast.FormalParameter;
import parser.ast.FormalParameterList;
import parser.ast.FormalParameterRest;
import parser.ast.Function;
import parser.ast.GreaterThanEqualExpression;
import parser.ast.GreaterThanExpression;
import parser.ast.HeatStatement;
import parser.ast.Identifier;
import parser.ast.Instruction;
import parser.ast.IntegerLiteral;
import parser.ast.LessThanEqualExpression;
import parser.ast.LessThanExpression;
import parser.ast.Manifest;
import parser.ast.MatLiteral;
import parser.ast.MinusExpression;
import parser.ast.MixStatement;
import parser.ast.NatLiteral;
import parser.ast.NodeList;
import parser.ast.NodeListOptional;
import parser.ast.NodeOptional;
import parser.ast.NodeSequence;
import parser.ast.NodeToken;
import parser.ast.NotEqualExpression;
import parser.ast.NotExpression;
import parser.ast.OrExpression;
import parser.ast.ParenthesisExpression;
import parser.ast.PlusExpression;
import parser.ast.PrimaryExpression;
import parser.ast.RealLiteral;
import parser.ast.RepeatStatement;
import parser.ast.SplitStatement;
import parser.ast.Statement;
import parser.ast.Stationary;
import parser.ast.TimesExpression;
import parser.ast.TrueLiteral;
import parser.ast.Type;
import parser.ast.TypingList;
import parser.ast.TypingRest;
import parser.ast.WhileStatement;

/**
 * All GJ void visitors must implement this interface.
 */

public interface GJVoidVisitor<A> {

    //
    // GJ void Auto class visitors
    //

    void visit(NodeList n, A argu);

    void visit(NodeListOptional n, A argu);

    void visit(NodeOptional n, A argu);

    void visit(NodeSequence n, A argu);

    void visit(NodeToken n, A argu);

    //
    // User-generated visitor methods below
    //

    /**
     * f0 -> Stationary()
     * f1 -> Manifest()
     * f2 -> <INSTRUCTIONS>
     * f3 -> Instruction()
     * f4 -> <EOF>
     */
    void visit(BSProgram n, A argu);

    /**
     * f0 -> ( <STATIONARY> Identifier() )*
     */
    void visit(Stationary n, A argu);

    /**
     * f0 -> ( <MANIFEST> Identifier() )*
     */
    void visit(Manifest n, A argu);

    /**
     * f0 -> Instruction()
     * | BranchStatement()
     * | WhileStatement()
     */
    void visit(Statement n, A argu);

    /**
     * f0 -> MixStatement()
     * | SplitStatement()
     * | DrainStatement()
     * | HeatStatement()
     * | DetectStatement()
     * | RepeatStatement()
     * | AssignmentStatement()
     */
    void visit(Instruction n, A argu);

    /**
     * f0 -> <FUNCTION>
     * f1 -> Identifier()
     * f2 -> <LPAREN>
     * f3 -> FormalParameterList()
     * f4 -> <RPAREN>
     * f5 -> ( <COLON> ( TypingList() )* )?
     * f6 -> <LBRACE>
     * f7 -> Statement()
     * f8 -> <LBRACE>
     */
    void visit(Function n, A argu);

    /**
     * f0 -> Type()
     * f1 -> ( TypingRest() )*
     */
    void visit(TypingList n, A argu);

    /**
     * f0 -> <COMMA>
     * f1 -> Type()
     */
    void visit(TypingRest n, A argu);

    /**
     * f0 -> FormalParameter()
     * f1 -> ( FormalParameterRest() )*
     */
    void visit(FormalParameterList n, A argu);

    /**
     * f0 -> TypingList()
     * f1 -> Identifier()
     */
    void visit(FormalParameter n, A argu);

    /**
     * f0 -> <COMMA>
     * f1 -> FormalParameter()
     */
    void visit(FormalParameterRest n, A argu);

    /**
     * f0 -> <MIX> PrimaryExpression() <WITH> PrimaryExpression()
     * | <FOR> IntegerLiteral()
     */
    void visit(MixStatement n, A argu);

    /**
     * f0 -> <SPLIT>
     * f1 -> PrimaryExpression()
     * f2 -> <INTO>
     * f3 -> PrimaryExpression()
     */
    void visit(SplitStatement n, A argu);

    /**
     * f0 -> <DRAIN>
     * f1 -> PrimaryExpression()
     */
    void visit(DrainStatement n, A argu);

    /**
     * f0 -> <HEAT> PrimaryExpression() <AT> IntegerLiteral()
     * | <FOR> IntegerLiteral()
     */
    void visit(HeatStatement n, A argu);

    /**
     * f0 -> <DETECT> Identifier() <ON> PrimaryExpression()
     * | <FOR> <INTEGER_LITERAL>
     */
    void visit(DetectStatement n, A argu);

    /**
     * f0 -> WhileStatement()
     */
    void visit(RepeatStatement n, A argu);

    /**
     * f0 -> ( TypingList() )*
     * f1 -> Identifier()
     * f2 -> <ASSIGN>
     * f3 -> Expression()
     */
    void visit(AssignmentStatement n, A argu);

    /**
     * f0 -> MatLiteral()
     * | NatLiteral()
     * | RealLiteral()
     */
    void visit(Type n, A argu);

    /**
     * f0 -> <IF> <LPAREN> Expression() <RPAREN> <LBRACE> Statement() <RBRACE>
     * | <ELSE_IF> <LPAREN> Expression() <RPAREN> <LBRACE> Statement() <RBRACE>
     * | <ELSE> <LBRACE> Statement() <RBRACE>
     */
    void visit(BranchStatement n, A argu);

    /**
     * f0 -> <REPEAT>
     * f1 -> IntegerLiteral()
     * f2 -> <TIMES>
     * f3 -> <LBRACE>
     * f4 -> Statement()
     * f5 -> <RBRACE>
     */
    void visit(WhileStatement n, A argu);

    /**
     * f0 -> IntegerLiteral()
     * | TrueLiteral()
     * | FalseLiteral()
     * | Identifier()
     * | ParenthesisExpression()
     */
    void visit(PrimaryExpression n, A argu);

    /**
     * f0 -> <INTEGER_LITERAL>
     */
    void visit(IntegerLiteral n, A argu);

    /**
     * f0 -> <NAT>
     */
    void visit(NatLiteral n, A argu);

    /**
     * f0 -> <MAT>
     */
    void visit(MatLiteral n, A argu);

    /**
     * f0 -> <REAL>
     */
    void visit(RealLiteral n, A argu);

    /**
     * f0 -> <TRUE>
     */
    void visit(TrueLiteral n, A argu);

    /**
     * f0 -> <FALSE>
     */
    void visit(FalseLiteral n, A argu);

    /**
     * f0 -> <IDENTIFIER>
     */
    void visit(Identifier n, A argu);

    /**
     * f0 -> AndExpression()
     * | LessThanExpression()
     * | LessThanEqualExpression()
     * | GreaterThanExpression()
     * | GreaterThanEqualExpression()
     * | NotEqualExpression()
     * | EqualityExpression()
     * | OrExpression()
     * | PlusExpression()
     * | MinusExpression()
     * | TimesExpression()
     * | PrimaryExpression()
     */
    void visit(Expression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> <AND>
     * f2 -> PrimaryExpression()
     */
    void visit(AndExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> <LESSTHAN>
     * f2 -> PrimaryExpression()
     */
    void visit(LessThanExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> <LESSTHANEQUAL>
     * f2 -> PrimaryExpression()
     */
    void visit(LessThanEqualExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> <GREATERTHAN>
     * f2 -> PrimaryExpression()
     */
    void visit(GreaterThanExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> <GREATERTHANEQUAL>
     * f2 -> PrimaryExpression()
     */
    void visit(GreaterThanEqualExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> <NOTEQUAL>
     * f2 -> PrimaryExpression()
     */
    void visit(NotEqualExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> <OR>
     * f2 -> PrimaryExpression()
     */
    void visit(EqualityExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> <LESSTHAN>
     * f2 -> PrimaryExpression()
     */
    void visit(OrExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> <ADD>
     * f2 -> PrimaryExpression()
     */
    void visit(PlusExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> <MINUS>
     * f2 -> PrimaryExpression()
     */
    void visit(MinusExpression n, A argu);

    /**
     * f0 -> PrimaryExpression()
     * f1 -> <MULTIPLY>
     * f2 -> PrimaryExpression()
     */
    void visit(TimesExpression n, A argu);

    /**
     * f0 -> <BANG>
     * f1 -> Expression()
     */
    void visit(NotExpression n, A argu);

    /**
     * f0 -> <LPAREN>
     * f1 -> Expression()
     * f2 -> <RPAREN>
     */
    void visit(ParenthesisExpression n, A argu);

}

